### ISSUE TITLE
casing in paths or ctmouse.asm

### ISSUE THREAD

**Issue by sweetlilmre** [davidebreso/ctmouse#2]
Thank you for this port. 

Compilation was relatively straight forward using JWasm from: https://github.com/Baron-von-Riedesel/JWasm
However there were issues with the case of some files / directories.
`ctmouse.asm` includes files from e.g. `DOS` and `BIOS`, while the directories are cased as `dos` and `bios` (there are a few other similar issues).

I patched `ctmouse.asm` as per below. Would you like a pull request to sort this out?

```
56c56
< include asmlib/BIOS/area0.def ; ** int11 flags and various 40:xx gfx info
---
> include asmlib/bios/area0.def ; ** int11 flags and various 40:xx gfx info
63,66c63,66
< include asmlib/DOS/MCB.def    ; ** small, used to set ownerid and name
< include asmlib/DOS/PSP.def    ; ** only DOS_exit env_seg cmdline_len PSP_TSR used
< ; include asmlib/DOS/file.mac ; was only used once - DOSCloseFile
< include asmlib/DOS/mem.mac
---
> include asmlib/dos/mcb.def    ; ** small, used to set ownerid and name
> include asmlib/dos/psp.def    ; ** only DOS_exit env_seg cmdline_len PSP_TSR used
> ; include asmlib/dos/file.mac ; was only used once - DOSCloseFile
> include asmlib/dos/mem.mac
70c70
< include asmlib/hard/UART.def
---
> include asmlib/hard/uart.def
```

**Comment by sweetlilmre** [comment]
PR submitted.

**Comment by davidebreso** [comment]
Thank you for the PR. I am on a case-insensitive system so I never realized that there were issues.
